parameters:
    redis_url: '%env(string:REDIS_URL)%'

framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: avast/interview_app

        default_redis_provider: '%redis_url%'

        # Redis
        app: cache.adapter.redis_tag_aware
