parameters:
    redis_url: '%env(string:REDIS_URL)%'

framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # Redis
        app: cache.adapter.redis_tag_aware

        # Namespaced pools use the above "app" backend by default
        pools:
            cache.redis:
                provider: provider.redis
                tags: true
