imports:
    - { resource: 'validation/config_schema.yaml' }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $configSchema: '%config_schema%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    logger.disableable:
      class: App\Logger\DisableableLogger

    App\Logger\DisableableLoggerInterface: '@logger.disableable'

    App\Cache\CacheInterface: '@App\Cache\Adapter\RedisCacheAdapter'

    App\Parser\FormatParser\XMLFormatParser:
        bind:
            App\Validator\ConfigValidatorInterface: '@App\Validator\XMLConfigValidator'
            $nodeParsers:
                - '@App\Parser\XMLNodeParser\SubdomainsParser'
                - '@App\Parser\XMLNodeParser\CookiesParser'

    App\Parser\ConfigParser:
        bind:
            $parsers:
                - '@App\Parser\FormatParser\XMLFormatParser'
